#!/usr/bin/env python3
print("  // Section: memory users")
print("  // Generated by {}".format(__file__))
for i in range(0, 21):
  print("  assign cell{}ToUser = wProcessAllocatorEnabled && coreMessagePid                   == {} ? `USER_PROCESSOR_0 :".format(i,i))
  print("                        wProcessAllocatorEnabled && processAllocatorTargetMemoryCell == {} ? `USER_PROCESSOR_1 :".format(i))
  print("                        wMessageDeliveryEnabled  && messageDeliveryTargetPid         == {} ? `USER_PROCESSOR_0 :".format(i))
  print("                                                    core0Pid                         == {} ? `USER_CORE_0 :".format(i))
  print("                                                    core1Pid                         == {} ? `USER_CORE_1 :".format(i))
  print("                                                                                             `USER_UNUSED;")

